### ISSUE TITLE
REGRESSION Adb port doesn't get properly handoverd to chromedriver

### ISSUE THREAD

**Issue by aluedeke** [appium/appium-chromedriver#11]
check https://github.com/appium/appium/commit/b688a6e400812d0f36485167f255ac11f2bf51be

here @lbielski fixed that the chromedriver uses the adb port configured for appium. Without beeing able to configure a custome adb port its nearly impossible to use it in a large real device setup (tons of devices connected to the same host)

@Jonahss @jlipps Does anyone know why this has been removed?

**Comment by jlipps** [comment]
fixed by https://github.com/appium/appium-chromedriver/commit/e3e9638c893f1e0d6350691310ade4092a8a252c

**Comment by aluedeke** [comment]
@jlipps any chance to get that fixed and released in 1.4.x?

**Comment by jlipps** [comment]
@aluedeke are you saying that a change is still required in appium itself to make this work?

**Comment by aluedeke** [comment]
appium still depends on appium-chromdriver 2.3.2, this fix was made in 2.3.3 as far as i can see. so this fix is still not released

**Comment by jlipps** [comment]
hi @aluedeke all our efforts right now are on getting 1.5 out the door, but we can definitely make this change in the 1.4 branch soon
